[package]
name = "rust_microservice"
version = "0.1.0"
authors = ["Anthony Comstock <comstoan@gmail.com>"]

[dependencies]
env_logger = "0.5.3"
log = "0.4.1"
futures = "0.1.17"
hyper = "0.11.13"
url = "1.7.2"
serde_json = "1.0.33"
